### PR TITLE
DT-118: Implement "Fix with AI" for SQL query optimization

### LINKED ISSUE #118: Implement "Fix with AI" for SQL query optimization

### PR DESCRIPTION
**Pull request by abdotop**
Implement AI-based SQL query optimization analysis feature

### CODE REVIEW

File: api/fix-query.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+import { promptTemplate } from '/api/fix-query-prompt.ts'
+import { GEMINI_API_KEY, GEMINI_MODEL } from '/api/lib/env.ts'
+
+const GEMINI_URL =
+  `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:streamGenerateContent?alt=json&key=${GEMINI_API_KEY}`
+
+export async function analyzeQueryWithAI(metric: unknown, schema: unknown) {
+  const payload = JSON.stringify({ schema, metrics: [metric] }, null, 2)
+  const prompt = promptTemplate.replace('{{QUERY_METRICS_JSON}}', payload)
```
Comment (kigiri) [inline api/fix-query.ts]: rename `QUERY_METRICS_JSON` by `QUERY_DETAILS_JSON`

File: api/routes.ts [hunk 2]
```diff
@@ -693,36 +720,35 @@ const defs = {
...
+    output: ARR(MetricSchema, 'Collected query metrics'),
     description: 'Get SQL metrics from the deployment',
   }),
+  'POST/api/deployment/fix-query': route({
+    authorize: withUserSession,
+    fn: async (ctx, { id, deployment, metric }) => {
+      await withDeploymentTableAccess(ctx, deployment)
+      const schema = DatabaseSchemasCollection.get(deployment)
+      try {
+        const analysis = await analyzeQueryWithAI(metric, schema)
```
Comment (kigiri) [inline api/routes.ts:732]: I would convert markdown to HTML here in the backend instead of doing it in the front end

File: web/pages/DeploymentPage.tsx [hunk 3]
```diff
@@ -1482,6 +1484,188 @@ function buildExplainTree(rows: MetricExplain): ExplainNode[] {
...
+  if (!metric) return
+  fixQueryApi.fetch({ id: metric.id, deployment: dep, metric })
+})
+
+// Populate cache using fetchingFor — not url.params.expanded which may have changed
+effect(() => {
+  const data = fixQueryApi.data
+  if (!data) return
+  untracked(() => {
+    if (!analysisCache.value.has(data.id)) {
```
Comment (kigiri) [inline web/pages/DeploymentPage.tsx]: use `.peek()` instead of `untracked`

File: web/pages/DeploymentPage.tsx [hunk 4]
```diff
@@ -1482,6 +1484,75 @@ function buildExplainTree(rows: MetricExplain): ExplainNode[] {
...
+  fixQueryApi.fetch({ id: metric.id, deployment: dep, metric })
+})
+
+// Populate cache using fetchingFor — not url.params.expanded which may have changed
+effect(() => {
+  const data = fixQueryApi.data
+  if (!data) return
+  const cashe = analysisCache.peek()
+
+  if (!cashe.has(data.id)) {
```
Comment (kigiri) [inline web/pages/DeploymentPage.tsx:1509]: Image

**Review by kigiri — APPROVED** [review]
